#!/bin/bash
Fore=255
Back=0
if [ "$2" = "Red" ]
then
#	printf "\e[48;5;${Back}m \e[38;5;${Fore}m"
	Back=128
fi

doit(){
	printf "\e[48;5;${Back}m \e[38;5;${Fore}m %s %s %s\n\e[0m" $1 $2 $3
}

ls -lh $1 | awk 'BEGIN{printf "%-5s %-26s %-10s\n", "", "NAME", "SIZE"}
{
	if ($1 != "total") {
	FILE = "📄";
	DIR = "📁";
	PROG = "💾";
	A = FILE;
	B = substr($1,1,1);
	B1 = substr($1,4,1);
	B2 = substr($1,7,1);
	B3 = substr($1,10,1);
	if (B=="d") A = DIR;
	if (B=="-" && (B1 == "x" || B2 == "x" || B3 == "x")) A = PROG;
		system("printf {%s %s %s\n} A $9 $7);
	}
}'
printf "\e[0m"
